### PR TITLE
Simplify device choosing dialog

### PR DESCRIPTION
**Pull request by gal20**
This PR adds colors make device choosing easier in more complex cases.
For example, Using one Combined Joy-Cons device and two individual Joy-Cons:
colorscombinnedone
Or, using two Combined Joy-Cons devices:
colorscombinedtwo
The different controllers are much easier to distinguish compared to master, where you'll have to check which macs appear twice to distinguish between individual and paired Joy-Cons.
colorhintsno_cropped

### CODE REVIEW

**Comment by joaorb64** [comment]
I've never used multiple combined joycons and yes that looks like it's complicated to setup as is.
I really like the idea, but is there a way we could have this without having to assimilate the colors to the options we see? I'm thinking that something like a 🔗 emoji, if it isn't too cheesy, could be easier to understand. Or you could reorder them to have the unassigned ones first, if that makes sense...?

**Comment by gal20** [comment]
I agree with the emoji suggestion, it would be more consistent with the rest of the code and colorblind friendly. I'll try to rework it soon.

**Comment by gal20** [comment]
I was wondering whether the auto-assigned and manually assigned devices should be printed at all. It doesn't really make sense to choose the same motion device twice, and could only cause bugs, since the same device is handled by two different threads. It would be easier to just skip them and not allow the user to choose them.

**Comment by gal20** [comment]
Pushed a new branch to instead filter out the assigned motion devices.

**Comment by joaorb64** [comment]
Perfect :)

**Comment by joaorb64** [comment]
Now that I come to think about it, if the list has only a left and a right joycons we could have automatic assignment...?
I don't know how would running the program after 2 merged joycons are already connected would work, but we could see if the evdev devices' order is static or something...?

**Comment by gal20** [comment]
> Now that I come to think about it, if the list has only a left and a right joycons we could have automatic assignment...?

It is possible to make that a special case. I don't think it's currently possible to assign automatically with two Combined devices though.

**Comment by joaorb64** [comment]
Yeah, if joycond mantained a file mapping left joycon mac to right joycon mac that could make it so joycond-cemuhook could be turned into a system service.

**Pull request merged**
